// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPJWebW9NHQoR-TzPZp-qD5-qbM-D_sU',
    appId: '1:257993973105:web:4ce3354755d859f0b5aad0',
    messagingSenderId: '257993973105',
    projectId: 'nada-188d5',
    authDomain: 'nada-188d5.firebaseapp.com',
    storageBucket: 'nada-188d5.firebasestorage.app',
    measurementId: 'G-QSJ9PPW5DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3B_0SrPicmnbnM1JXWjmIst7ZZ_t2XQ',
    appId: '1:257993973105:android:6d8fdc41e8894c4eb5aad0',
    messagingSenderId: '257993973105',
    projectId: 'nada-188d5',
    storageBucket: 'nada-188d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3HFByxgI_ui9NzTgUwKXD2A8tnQNBqds',
    appId: '1:257993973105:ios:a928bc4f9470bf1db5aad0',
    messagingSenderId: '257993973105',
    projectId: 'nada-188d5',
    storageBucket: 'nada-188d5.firebasestorage.app',
    iosBundleId: 'com.example.pageBegin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3HFByxgI_ui9NzTgUwKXD2A8tnQNBqds',
    appId: '1:257993973105:ios:a928bc4f9470bf1db5aad0',
    messagingSenderId: '257993973105',
    projectId: 'nada-188d5',
    storageBucket: 'nada-188d5.firebasestorage.app',
    iosBundleId: 'com.example.pageBegin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSPJWebW9NHQoR-TzPZp-qD5-qbM-D_sU',
    appId: '1:257993973105:web:6eb5c30f26b48a20b5aad0',
    messagingSenderId: '257993973105',
    projectId: 'nada-188d5',
    authDomain: 'nada-188d5.firebaseapp.com',
    storageBucket: 'nada-188d5.firebasestorage.app',
    measurementId: 'G-0T3XWVDE4E',
  );
}
